version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_DATABASE: advertising_banners
      MYSQL_USER: banners_user
      MYSQL_PASSWORD: banners_user_password
      MYSQL_ROOT_PASSWORD: test_root
    ports:
      - 3306:3306
    expose:
      - 3306

  advertising-banner-back:
    image: tigrulya/advertising-banner-back
    depends_on:
      - mysql
    environment:
      DB_USERNAME: banners_user
      DB_PASSWORD: banners_user_password
      DB_HOSTNAME: mysql
    ports:
      - 8080:8080
    expose:
      - 8080

  advertising-banner-front:
    image: tigrulya/advertising-banner-front
    depends_on:
      - advertising-banner-back
    ports:
      - 80:80
    expose:
      - 80
