version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'advertising_banners'
      MYSQL_USER: 'banners_user'
      MYSQL_PASSWORD: 'banners_user_password'
      MYSQL_ROOT_PASSWORD: 'test_root'
    ports:
      - 3306:3306
    expose:
      - 3306